services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - workshop-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U n8n"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - workshop-network

  # n8n
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=development
      - WEBHOOK_URL=https://${CODESPACE_NAME}-5678.app.github.dev/
      - N8N_EDITOR_BASE_URL=https://${CODESPACE_NAME}-5678.app.github.dev/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_SECURE_COOKIE=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN=true
      - NODE_OPTIONS=--max-old-space-size=2048
      - N8N_DISABLE_UI=false
      - N8N_CORS_ORIGIN=*
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=true
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - N8N_USER_MANAGEMENT_DISABLED=false
      - N8N_OWNER_EMAIL=admin@workshop.com
      - N8N_OWNER_PASSWORD=workshop123
      - N8N_USER_MANAGEMENT_JWT_SECRET=workshop-jwt-secret
      - N8N_PUSH_BACKEND=websocket
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_TEMPLATES_ENABLED=false
      - N8N_HIRING_BANNER_ENABLED=false
      - EXECUTIONS_TIMEOUT=3600
      - EXECUTIONS_TIMEOUT_MAX=7200

    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - workshop-network

  evolution-api:
    image: atendai/evolution-api:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env

    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    depends_on:
      - postgres-evolution
      - redis-evolution
    networks:
      - workshop-network

  postgres-evolution:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: evolution
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: evolution
    volumes:
      - postgres_evolution_data:/var/lib/postgresql/data
    networks:
      - workshop-network

  redis-evolution:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_evolution_data:/data
    networks:
      - workshop-network

  evolution-manager:
    image: atendai/evolution-manager:latest
    restart: unless-stopped
    ports:
      - "8081:3000"
    environment:
      - NEXT_PUBLIC_EVOLUTION_API_URL=http://localhost:8080
    depends_on:
      - evolution-api
    networks:
      - workshop-network

volumes:
  postgres_data:
  postgres_evolution_data:
  redis_data:
  redis_evolution_data:
  n8n_data:
  evolution_instances:
  evolution_store:

networks:
  workshop-network:
    driver: bridge
